### ISSUE TITLE
6 BCOs populate by Ntino

### ISSUE THREAD

**Issue by tiwa1154** [biocompute-objects/portal_userdb#36]

**Comment by kee007ney** [comment]
Ntino sent one BCO 4/14/2023
Experienced server error with the others, will retry
Ntino will send, Tianyi will convert to BCO in Portal, Ntino will review (direct connection from Galaxy not functional)

**Comment by kee007ney** [comment]
Ntino has a few more workflows he wants to build, troubleshooting Galaxy issues. Submitted an issue to the Galaxy team (on 4/19/2023).

**Comment by tiwa1154** [comment]
https://github.com/galaxyproject/galaxy/issues/15961

**Comment by kee007ney** [comment]
Ntino responded 5/5/2023. Maurius van den Beek (lead Dev) self assigned the ticket.

**Comment by mvdbeek** [comment]
The fix should be on usegalaxy.org later today. The underlying problem is that the workflow didn't have a label assigned to one of the input steps. I'd recommend always doing that, and also for as far as reasonable going through the best practice panel in the workflow editor that will warn you about these things.

<img width="456" alt="Screenshot 2023-05-12 at 16 19 01" src="https://github.com/biocompute-objects/portal_userdb/assets/6804901/cf4be4a3-8614-42ab-ad2d-55849aec1819">

**Comment by kee007ney** [comment]
Tiany will reach out to Ntino and see if the fix works.

**Comment by tiwa1154** [comment]
Contacted Ntino, he has been busy with the school work. I am taking next week off so we will have a meeting on the week of Jun 12th

**Comment by kee007ney** [comment]
Tianyi to ask Ntino to share permissions on dependencies so that she can rerun the BCOs.

**Comment by kee007ney** [comment]
Tianyi will check in on status today.

**Comment by kee007ney** [comment]
No reply, Tianyi to send a follow up.

**Comment by tiwa1154** [comment]
Recreated 2 BCOs based on the updates Ntino sent. 
Staphylococcus genome assembly: https://www.biocomputeobject.org/builder?https://biocomputeobject.org/GALXY_000024/DRAFT
CHIPSeq: https://biocomputeobject.org/builder?https://biocomputeobject.org/GALXY_000025/DRAFT

Haven't heard back since Sept 26th.
