### ISSUE TITLE
"Something went wrong." (description domain)

### ISSUE THREAD

**Issue by Kirans0615** [biocompute-objects/portal_userdb#393]
**Describe the bug**
After saving draft BCO and referring back to it later description domain says "something went wrong." but the contents I put in before still exist in the tree view.
Object ID: https://biocomputeobject.org/BCO_000497/DRAFT

**To Reproduce**
1. Complete BCO and Save Draft
2. Copy link and refer to it later
3. See error in description domain

**Expected behavior**
Expected to still be able to edit and change description domain,

**Screenshots**
![issue2](https://github.com/biocompute-objects/portal_userdb/assets/166645524/0bd066a0-9991-4055-96f4-5842e8c77d27)
![issue1](https://github.com/biocompute-objects/portal_userdb/assets/166645524/289ab56c-ca2b-4d63-bd70-2cf5252b46b9)
![issue3](https://github.com/biocompute-objects/portal_userdb/assets/166645524/6bb6c6f9-b781-4b3b-b2a4-b43e4c545335)

**Desktop (please complete the following information):**
 - Windows
 - Chrome

**Smartphone (please complete the following information):**
 - Iphone 12

**Additional context**

**Comment by HadleyKing** [comment]
Using the `inspect` and looking at the `console` tab we can see that the browser complains because the `output_list` is a `NULL` when the browser expects it to have a value. 

![Screenshot 2024-07-12 at 9 06 45 AM](https://github.com/user-attachments/assets/667d0125-f2f0-4806-af3e-6c5946578a46)

Solution: 
- [ ] add error handling for this situation to the `description_domain` in the builder page.
