### ISSUE TITLE
Saving BCO Error on TST

### ISSUE THREAD

**Issue by Kirans0615** [biocompute-objects/portal_userdb#405]
**Describe the bug**
When you go to BCODB and check if your BCO is visible after validating and saving it you get the alert: Request Failed with Status Code 403. I have tried reloading many times and keep getting the same error. This error existed after uploading RAW JSON views too, sometimes giving the error 400 instead. This issue only exists on TST not PRD.

**To Reproduce**
1. Go to BCODB and check if your BCO is visible under "MY BCO"

**Expected behavior**
BCOs saved and validated should be shown.

**Screenshots**
![Capture](https://github.com/biocompute-objects/portal_userdb/assets/166645524/15147437-58ca-4491-9111-9abb9e55e7e7)

**Comment by tiwa1154** [comment]
I have the same issue. 

However, I can view stored BCOs if I use the filter function.

**Comment by HadleyKing** [comment]
On TEST, when navigating to `https://test.portal.biochemistry.gwu.edu/bcodbs` on the initial load the server returns a `403` error. This is an authentication error.  
![Screenshot 2024-07-12 at 8 53 39 AM](https://github.com/user-attachments/assets/64dafb25-d85d-4007-86b7-24205308af94)

Using the `inspect` panel we can see that is the error message returned from the BCODB: 
![Screenshot 2024-07-12 at 8 55 00 AM](https://github.com/user-attachments/assets/88ba80fd-b96d-43b7-9384-75db4c5f4907)

Since this error is present in TEST but not PRD we can guess that it is a problem with the token that is submitted for the search on the initial render. 
This is the request from a local deployment that succeeds:
![Screenshot 2024-07-12 at 8 59 25 AM](https://github.com/user-attachments/assets/38c6f347-84d0-4e93-ba2b-c887999fed84)

And this the the same from the TEST deployment that does not pass:
![Screenshot 2024-07-12 at 9 00 28 AM](https://github.com/user-attachments/assets/a547af4a-4d41-4e38-84f8-c8be6f432eef)

**Comment by tiwa1154** [comment]
Fix environment file on the test server

**Comment by tiwa1154** [comment]
Hadley fixed the issue
